name: scala-steward
on:
  push:
    branches: [ master ]
  schedule:
  - cron: '0 2 * * *'
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Launch Scala Steward
      if: ${{ !github.event.repository.fork }}
      uses: scala-steward-org/scala-steward-action@v2.9.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
